<a href="https://colab.research.google.com/github/Aadishah17/CollabLearn/blob/main/Data_Analysis_Practicals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
import statistics as stats

In [21]:
# Create NumPy array
arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))

Array: [10 20 30 40 50]
Mean: 30.0
Max: 50
Min: 10
Standard Deviation: 14.142135623730951

In [22]:
# Create DataFrame
data = {
    'Name': ['Aadi', 'CHETAN', 'UTSAV', 'AKSHAY'],
    'Marks': [85, 90, 78, 88]
}

df = pd.DataFrame(data)
df

     Name  Marks
0    Aadi     85
1  CHETAN     90
2   UTSAV     78
3  AKSHAY     88

In [23]:
print("Average Marks:", df['Marks'].mean())
print("Highest Marks:", df['Marks'].max())
print("Lowest Marks:", df['Marks'].min())

Average Marks: 85.25
Highest Marks: 90
Lowest Marks: 78

In [24]:
marks = df['Marks'].tolist()

print("Mean:", stats.mean(marks))
print("Median:", stats.median(marks))
print("Mode:", stats.mode(marks))

Mean: 85.25
Median: 86.5
Mode: 85

In [25]:
import numpy as np

b = np.array([
    [10, 20, 30, 50, 10],
    [1, 2, 3, 5, 6],
    [1, 1, 1, 1, 1]
])

print(b)
print("Dim:", b.ndim)
print("Shape:", b.shape)
print("Size:", b.size)
print("Item Size:", b.itemsize)
print("Data type:", b.dtype)

[[10 20 30 50 10]
 [ 1  2  3  5  6]
 [ 1  1  1  1  1]]
Dim: 2
Shape: (3, 5)
Size: 15
Item Size: 8
Data type: int64

In [26]:
c = np.empty((5, 5))
c

array([[ 2.43664739e-315,  0.00000000e+000, -5.25394651e+127,
         5.61154995e-312,  1.03594137e-308],
       [ 6.01347002e-154,  5.03961303e-266,  1.06317887e+248,
         1.69375610e+190,  6.23894434e-085],
       [ 1.06317887e+248,  6.05426619e-310,  6.98946779e-251,
        -7.92606478e-153,  1.44869607e-203],
       [ 3.33089147e+065,  2.63896495e-227, -2.73167484e+256,
         5.55308263e-222,  2.18003303e-149],
       [ 7.42786658e-223, -2.17200422e+001,  3.42664634e-277,
         1.72353484e-232, -4.02975323e+079]])

In [27]:
d = np.arange(0, 100, 2)
d

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [28]:
e = np.reshape(d, (10, 5))
e

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [29]:
f = np.reshape(e, (2, 5, 5))
print(f)

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]

In [30]:
print("Last element:", d[-1])

Last element: 98

In [31]:
print("Element upto 10:", d[:10])

Element upto 10: [ 0  2  4  6  8 10 12 14 16 18]

In [32]:
print("Last 5 element:", d[-5:])

Last 5 element: [90 92 94 96 98]

In [33]:
print("Alternative Numbers:", d[::2])

Alternative Numbers: [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]

In [34]:
import pandas as pd

In [35]:
p_dict = {
    'pid': [1, 2, 3, 4, 5],
    'pname': ['A', 'B', 'C', 'D', 'E'],
    'price': [10, 20, 30, 40, 50],
    'vendor': ['V1', 'V2', 'V3', 'V4', 'V5']
}

p_dict

{'pid': [1, 2, 3, 4, 5],
 'pname': ['A', 'B', 'C', 'D', 'E'],
 'price': [10, 20, 30, 40, 50],
 'vendor': ['V1', 'V2', 'V3', 'V4', 'V5']}

In [36]:
grt = pd.DataFrame(p_dict)
grt

   pid pname  price vendor
0    1     A     10     V1
1    2     B     20     V2
2    3     C     30     V3
3    4     D     40     V4
4    5     E     50     V5